Добавляет разметку всех страниц
htmlacademy-htmlcss/1891505-gllacy-35 pull request #2
Opened 2022-09-27 18:18 UTC by JuliyaPigulina

2022-09-28 07:59 UTC, Safyann requested changes
Хорошо, но есть несколько доработок

2022-09-28 07:59 UTC, Safyann commented on catalog.html
> +          <a class="product-card-button" href="#">
лучше сделать кнопкой, так как это действие добавить в корзину а не переходить на отдельную страницу

2022-09-28 07:59 UTC, Safyann commented on index.html
> +            <a class="button" href="#">Заказать</a>
лучше сделать кнопкой, так как это действие добавить в корзину а не переходить на отдельную страницу

2022-09-28 07:59 UTC, Safyann commented on index.html
> +        </ul>
картинки и текст - 1 слайд, когда разделяешь потм тяжело будет связать их логику, проще 1 слайд - это описание кнопка и изображение

2022-09-28 07:59 UTC, Safyann commented on index.html
> +            <a class="popular-card-button" href="#">
лучше сделать кнопкой, так как это действие добавить в корзину а не переходить на отдельную страницу

2022-09-28 07:59 UTC, Safyann commented on index.html
> +          </form>
все три поля - это 1 форма, не надо каждый инпут оборачивать в form, это тег используется для всей формы

2022-09-30 09:28 UTC, JuliyaPigulina commented
Разметка всех страниц (доработки)

2022-09-30 11:15 UTC, merged